### ISSUE TITLE
Should Quicklink be a requirement?

### ISSUE THREAD

**Issue by thejimbirch** [bluehorndigital/drupal-testing-workshop#3]
https://github.com/bluehorndigital/drupal-testing-workshop/blob/0c586277dbedbdf128ee276ccb71938ff702a9f0/composer.json#L22

**Comment by mglaman** [comment]
Yes, it's used as an example. This will be a project that I use for various testing workshops through Bluehorn Digital. My goal is to have a wide array of tests.

And testing `drupal/quicklink` is faster than `--tag core`

**Comment by thejimbirch** [comment]
Excellent!  I thought it was only for core.  Closing this issue.

**Comment by mglaman** [comment]
It's going to start for just Drupal core, but I figure folks are going to want to write tests for their contrib as well. And Quicklink is the one time I've written a Nightwatch test in contrib
